import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSalesRelatedEntites1753890594667 implements MigrationInterface {
    name = 'AddSalesRelatedEntites1753890594667'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_21e5378da63923ebbf3e19f0201"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_22ff38e6b64c73d008e601d5c59"`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_type_enum" AS ENUM('percentage', 'fixed', 'bogo', 'bulk_discount')`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "description" text, "code" character varying(50), "type" "public"."discounts_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "minimumOrderAmount" numeric(10,2), "maximumDiscountAmount" numeric(10,2), "usageLimit" integer, "usageCount" integer NOT NULL DEFAULT '0', "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "applyToAllProducts" boolean NOT NULL DEFAULT false, "applyToAllCustomers" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_8c7cc2340e9ea0fc5a246e63749" UNIQUE ("code"), CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "phoneNumber" character varying(20) NOT NULL, "baseCommissionRate" numeric(10,2) NOT NULL DEFAULT '0', "jobTitle" character varying(255), "userId" uuid, "shopId" uuid, "warehouseId" uuid, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_transactions_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_transactions_transactiontype_enum" AS ENUM('sale', 'return', 'refund', 'adjustment', 'transfer')`);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(10,2) NOT NULL, "paymentMethod" "public"."payment_transactions_paymentmethod_enum" NOT NULL, "transactionType" "public"."payment_transactions_transactiontype_enum" NOT NULL, "transactionReference" character varying(100), "notes" character varying(255), "transactionDate" TIMESTAMP NOT NULL DEFAULT now(), "paymentDetails" json, "isSuccessful" boolean NOT NULL DEFAULT true, "failureReason" character varying(255), "sale_id" uuid, "processed_by" uuid, CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(10,2) NOT NULL, "commissionDate" date NOT NULL, "commissionRate" numeric(10,2) NOT NULL, "commissionAmount" numeric(10,2) NOT NULL, "saleId" uuid, "productId" uuid, "employeeId" uuid, CONSTRAINT "PK_2701379966e2e670bb5ff0ae78e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'view', 'login', 'logout', 'export', 'import')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "entityType" character varying(100) NOT NULL, "entityId" uuid, "action" "public"."audit_logs_action_enum" NOT NULL, "oldValues" json, "newValues" json, "description" character varying(255), "ipAddress" character varying(45), "userAgent" character varying(500), "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discount_products" ("discount_id" uuid NOT NULL, "product_id" uuid NOT NULL, CONSTRAINT "PK_ec9bf243c94d07317493d1d6b28" PRIMARY KEY ("discount_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19155613d001de1ce3da8875d5" ON "discount_products" ("discount_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8857bc50a51861e155ce58ca41" ON "discount_products" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "discount_customers" ("discount_id" uuid NOT NULL, "customer_id" uuid NOT NULL, CONSTRAINT "PK_e29c47d0b96734d684d70dabe75" PRIMARY KEY ("discount_id", "customer_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f155905bf802cb04963b1a3849" ON "discount_customers" ("discount_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_57dd0c9475dd10cd30c4f84b86" ON "discount_customers" ("customer_id") `);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "salesId"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "discountAmount" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "taxRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "taxAmount" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "subtotal" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "sales_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "product_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "discount_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "discountAmount" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."sales_discounttype_enum" AS ENUM('percentage', 'fixed', 'bogo', 'bulk_discount')`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "discountType" "public"."sales_discounttype_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "discountRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "subtotal" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "invoiceNumber" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "UQ_4f4006dc362ea9cc6308b4fb23d" UNIQUE ("invoiceNumber")`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "dueDate" date`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "terms" text`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "shop_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "created_by" uuid`);
        await queryRunner.query(`ALTER TABLE "products" ADD "commissionRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "warehouse_products" ADD "quantity" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD "capacity" integer`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD "managerId" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'user', 'company_admin', 'manager', 'shop_employee', 'warehouse_employee')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."sales_paymenttype_enum" RENAME TO "sales_paymenttype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sales_paymenttype_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "paymentType" TYPE "public"."sales_paymenttype_enum" USING "paymentType"::"text"::"public"."sales_paymenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sales_paymenttype_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."sales_status_enum" RENAME TO "sales_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('pending', 'completed', 'cancelled', 'refunded', 'partially_paid', 'returned', 'draft')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sales_status_enum" USING "status"::"text"::"public"."sales_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95"`);
        await queryRunner.query(`ALTER TABLE "warehouses" ALTER COLUMN "companyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_00c5470b7884170bba20642b04c" FOREIGN KEY ("sales_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_2e62caaea771f155d11324a50fb" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_13b1ec740347b9d17257df3b9fe" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_737991e10350d9626f592894cef" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_9cb03e9df5b6c71b181d79720c2" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_ac44f15896b81599b45b8d6f4f0" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_b4ceb47b87c47ed55332ec20433" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_23d56e4b35636f1e61ffcb330df" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_4cc004d8ae1797e47e62635f7ac" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_83a12e5e2723eafe9a47c441457" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_122588f5d349bcae6e6e461490a" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_fb301c26b86f95256429a2e6981" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_5a6fdf4dae16704000b9711654d" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_1b722234d6e60702724d0d5b423" FOREIGN KEY ("managerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_products" ADD CONSTRAINT "FK_19155613d001de1ce3da8875d57" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_products" ADD CONSTRAINT "FK_8857bc50a51861e155ce58ca410" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_customers" ADD CONSTRAINT "FK_f155905bf802cb04963b1a38493" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_customers" ADD CONSTRAINT "FK_57dd0c9475dd10cd30c4f84b865" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "discount_customers" DROP CONSTRAINT "FK_57dd0c9475dd10cd30c4f84b865"`);
        await queryRunner.query(`ALTER TABLE "discount_customers" DROP CONSTRAINT "FK_f155905bf802cb04963b1a38493"`);
        await queryRunner.query(`ALTER TABLE "discount_products" DROP CONSTRAINT "FK_8857bc50a51861e155ce58ca410"`);
        await queryRunner.query(`ALTER TABLE "discount_products" DROP CONSTRAINT "FK_19155613d001de1ce3da8875d57"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_1b722234d6e60702724d0d5b423"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_5a6fdf4dae16704000b9711654d"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_fb301c26b86f95256429a2e6981"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_122588f5d349bcae6e6e461490a"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_83a12e5e2723eafe9a47c441457"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_4cc004d8ae1797e47e62635f7ac"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_23d56e4b35636f1e61ffcb330df"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_b4ceb47b87c47ed55332ec20433"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_ac44f15896b81599b45b8d6f4f0"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_9cb03e9df5b6c71b181d79720c2"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_737991e10350d9626f592894cef"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_13b1ec740347b9d17257df3b9fe"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_2e62caaea771f155d11324a50fb"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_00c5470b7884170bba20642b04c"`);
        await queryRunner.query(`ALTER TABLE "warehouses" ALTER COLUMN "companyId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum_old" AS ENUM('pending', 'completed', 'cancelled', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sales_status_enum_old" USING "status"::"text"::"public"."sales_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sales_status_enum_old" RENAME TO "sales_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."sales_paymenttype_enum_old" AS ENUM('cash', 'credit', 'debit', 'online')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "paymentType" TYPE "public"."sales_paymenttype_enum_old" USING "paymentType"::"text"::"public"."sales_paymenttype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sales_paymenttype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sales_paymenttype_enum_old" RENAME TO "sales_paymenttype_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('super_admin', 'admin', 'user', 'company_admin', 'manager')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP COLUMN "managerId"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP COLUMN "capacity"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "warehouse_products" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "commissionRate"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "shop_id"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "terms"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "dueDate"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "UQ_4f4006dc362ea9cc6308b4fb23d"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "invoiceNumber"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "subtotal"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "discountRate"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "discountType"`);
        await queryRunner.query(`DROP TYPE "public"."sales_discounttype_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "discountAmount"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "discount_id"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "sales_id"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "subtotal"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "taxAmount"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "taxRate"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "discountAmount"`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "productId" uuid`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "salesId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57dd0c9475dd10cd30c4f84b86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f155905bf802cb04963b1a3849"`);
        await queryRunner.query(`DROP TABLE "discount_customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8857bc50a51861e155ce58ca41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19155613d001de1ce3da8875d5"`);
        await queryRunner.query(`DROP TABLE "discount_products"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "commissions"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transactions_transactiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transactions_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_type_enum"`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_22ff38e6b64c73d008e601d5c59" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_21e5378da63923ebbf3e19f0201" FOREIGN KEY ("salesId") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
