import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPurchaseExpensesCreditModules1756111118552 implements MigrationInterface {
    name = 'AddPurchaseExpensesCreditModules1756111118552'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled', 'reversed')`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymenttype_enum" AS ENUM('payment', 'partial_payment', 'overpayment', 'refund', 'adjustment', 'write_off')`);
        await queryRunner.query(`CREATE TABLE "credit_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "paymentNumber" character varying(50) NOT NULL, "amount" numeric(12,2) NOT NULL, "paymentMethod" "public"."credit_payments_paymentmethod_enum" NOT NULL, "status" "public"."credit_payments_status_enum" NOT NULL DEFAULT 'pending', "paymentType" "public"."credit_payments_paymenttype_enum" NOT NULL DEFAULT 'payment', "paymentDate" date NOT NULL, "referenceNumber" character varying(100), "checkNumber" character varying(100), "bankAccount" character varying(255), "notes" text, "paymentDetails" json, "isReconciled" boolean NOT NULL DEFAULT false, "reconciledDate" date, "appliedToPrincipal" numeric(12,2) NOT NULL DEFAULT '0', "appliedToInterest" numeric(12,2) NOT NULL DEFAULT '0', "appliedToFees" numeric(12,2) NOT NULL DEFAULT '0', "credit_sales_id" uuid, "processed_by" uuid, "reconciled_by" uuid, CONSTRAINT "UQ_7d8df244a3285386e0e7ff4877d" UNIQUE ("paymentNumber"), CONSTRAINT "PK_c8bf096041d9d988603b649ee33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2205fee5ec7c833f542ca0bfd9" ON "credit_payments" ("paymentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe3afb7bec2966c3957bbed52" ON "credit_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecce1591ffad0b35998e629071" ON "credit_payments" ("paymentDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7d8df244a3285386e0e7ff4877" ON "credit_payments" ("paymentNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."credit_sales_status_enum" AS ENUM('active', 'partially_paid', 'fully_paid', 'overdue', 'written_off', 'disputed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."credit_sales_creditterms_enum" AS ENUM('net_15', 'net_30', 'net_45', 'net_60', 'net_90', 'custom')`);
        await queryRunner.query(`CREATE TABLE "credit_sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "creditNumber" character varying(50) NOT NULL, "status" "public"."credit_sales_status_enum" NOT NULL DEFAULT 'active', "creditTerms" "public"."credit_sales_creditterms_enum" NOT NULL DEFAULT 'net_30', "paymentTermsDays" integer NOT NULL DEFAULT '30', "issueDate" date NOT NULL, "dueDate" date NOT NULL, "totalCreditAmount" numeric(12,2) NOT NULL, "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "remainingBalance" numeric(12,2) NOT NULL DEFAULT '0', "interestRate" numeric(5,2) NOT NULL DEFAULT '0', "interestAmount" numeric(12,2) NOT NULL DEFAULT '0', "lateFeeAmount" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "termsAndConditions" text, "isDisputed" boolean NOT NULL DEFAULT false, "disputeReason" text, "lastReminderSent" date, "reminderCount" integer NOT NULL DEFAULT '0', "metadata" json, "sales_id" uuid, "customer_id" uuid, "created_by" uuid, CONSTRAINT "UQ_8fd1a880e6b7f5a0aebfdd0fd1c" UNIQUE ("creditNumber"), CONSTRAINT "PK_a920c89e4d1c1782275ba568592" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a4e583956e8fdaec7509bdf00" ON "credit_sales" ("issueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_59639f22c81a78f565317397d2" ON "credit_sales" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_13f726be006367743fa6f4b995" ON "credit_sales" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8fd1a880e6b7f5a0aebfdd0fd1" ON "credit_sales" ("creditNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_items_status_enum" AS ENUM('pending', 'ordered', 'partially_received', 'fully_received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL, "receivedQuantity" integer NOT NULL DEFAULT '0', "rejectedQuantity" integer NOT NULL DEFAULT '0', "unitCost" numeric(10,2) NOT NULL, "actualUnitCost" numeric(10,2) NOT NULL DEFAULT '0', "totalCost" numeric(10,2) NOT NULL, "actualTotalCost" numeric(10,2) NOT NULL DEFAULT '0', "discountRate" numeric(5,2) NOT NULL DEFAULT '0', "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."purchase_items_status_enum" NOT NULL DEFAULT 'pending', "expectedDeliveryDate" date, "actualDeliveryDate" date, "notes" text, "specifications" text, "metadata" json, "qualityChecked" boolean NOT NULL DEFAULT false, "qualityApproved" boolean NOT NULL DEFAULT true, "qualityNotes" text, "purchase_order_id" uuid, "product_id" uuid, CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2a8c41174bc84bc88ad449d782" ON "purchase_items" ("purchase_order_id", "product_id") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "purchase_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(12,2) NOT NULL, "paymentMethod" "public"."purchase_payments_paymentmethod_enum" NOT NULL, "status" "public"."purchase_payments_status_enum" NOT NULL DEFAULT 'pending', "paymentDate" date NOT NULL, "referenceNumber" character varying(100), "checkNumber" character varying(100), "bankAccount" character varying(255), "notes" text, "paymentDetails" json, "isReconciled" boolean NOT NULL DEFAULT false, "reconciledDate" date, "transactionNumber" character varying(50) NOT NULL, "purchase_order_id" uuid, "processed_by" uuid, "reconciled_by" uuid, CONSTRAINT "UQ_9e3e268f416fbe648c8508cfd5f" UNIQUE ("transactionNumber"), CONSTRAINT "PK_9765d702e073d3cdf9b1600792d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6e01fc2d8cf385bfc153d1564" ON "purchase_payments" ("paymentMethod") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c24beb35bae25c17c4ef994" ON "purchase_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ca7fd8e07266825408bced5e1" ON "purchase_payments" ("paymentDate") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_purchasetype_enum" AS ENUM('stock_purchase', 'service_purchase', 'asset_purchase', 'supply_purchase')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'ordered', 'partially_received', 'fully_received', 'closed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_approvalstatus_enum" AS ENUM('pending', 'approved', 'rejected', 'auto_approved')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_paymentstatus_enum" AS ENUM('unpaid', 'partially_paid', 'fully_paid', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "poNumber" character varying(50) NOT NULL, "purchaseType" "public"."purchase_orders_purchasetype_enum" NOT NULL DEFAULT 'stock_purchase', "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "approvalStatus" "public"."purchase_orders_approvalstatus_enum" NOT NULL DEFAULT 'pending', "paymentStatus" "public"."purchase_orders_paymentstatus_enum" NOT NULL DEFAULT 'unpaid', "orderDate" date NOT NULL, "expectedDeliveryDate" date, "actualDeliveryDate" date, "dueDate" date, "subtotal" numeric(12,2) NOT NULL, "taxAmount" numeric(12,2) NOT NULL DEFAULT '0', "discountAmount" numeric(12,2) NOT NULL DEFAULT '0', "discountRate" numeric(5,2) NOT NULL DEFAULT '0', "shippingCost" numeric(12,2) NOT NULL DEFAULT '0', "otherCharges" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL, "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "remainingAmount" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "terms" text, "approvalNotes" text, "supplierInvoiceNumber" character varying(100), "referenceNumber" character varying(100), "paymentTermsDays" integer NOT NULL DEFAULT '30', "isUrgent" boolean NOT NULL DEFAULT false, "metadata" json, "supplier_id" uuid, "created_by" uuid, "approved_by" uuid, "warehouse_id" uuid, "branch_id" uuid, "company_id" uuid, CONSTRAINT "UQ_2e0fc7a6605393a9bd691cdcebe" UNIQUE ("poNumber"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3253914487a9fa14a59831dba9" ON "purchase_orders" ("expectedDeliveryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_8be43e7dd0ae89d236418c690c" ON "purchase_orders" ("orderDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_5272ac3aa931eedb14cd8789d6" ON "purchase_orders" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2e0fc7a6605393a9bd691cdceb" ON "purchase_orders" ("poNumber") `);
        await queryRunner.query(`CREATE TABLE "purchase_receiving_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "orderedQuantity" integer NOT NULL, "receivedQuantity" integer NOT NULL, "rejectedQuantity" integer NOT NULL DEFAULT '0', "unitCost" numeric(10,2) NOT NULL, "totalCost" numeric(10,2) NOT NULL, "notes" text, "rejectionReason" text, "qualityChecked" boolean NOT NULL DEFAULT false, "qualityApproved" boolean NOT NULL DEFAULT true, "qualityNotes" text, "expiryDate" date, "batchInfo" json, "metadata" json, "receiving_id" uuid, "purchase_item_id" uuid, "product_id" uuid, CONSTRAINT "PK_c7141c1486e84e89fc812a3d726" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_receivings_status_enum" AS ENUM('pending', 'partial', 'complete', 'over_received')`);
        await queryRunner.query(`CREATE TABLE "purchase_receivings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "receivingNumber" character varying(50) NOT NULL, "receivingDate" date NOT NULL, "status" "public"."purchase_receivings_status_enum" NOT NULL DEFAULT 'pending', "supplierDeliveryNote" character varying(100), "carrierName" character varying(100), "trackingNumber" character varying(100), "notes" text, "damageNotes" text, "hasDiscrepancies" boolean NOT NULL DEFAULT false, "discrepancyNotes" text, "qualityControlPassed" boolean NOT NULL DEFAULT false, "qualityControlNotes" text, "attachments" json, "metadata" json, "purchase_order_id" uuid, "received_by" uuid, "quality_checked_by" uuid, "warehouse_id" uuid, CONSTRAINT "UQ_65b827b253a3e00953c2f572d96" UNIQUE ("receivingNumber"), CONSTRAINT "PK_1c21b7e5fd38c6f6644e48a571d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4628685050edbefe5a1e7e96aa" ON "purchase_receivings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_289617b91e6c6f79acf5ef3f11" ON "purchase_receivings" ("receivingDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65b827b253a3e00953c2f572d9" ON "purchase_receivings" ("receivingNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."expense_approvals_approvallevel_enum" AS ENUM('manager', 'senior_manager', 'finance_head', 'cfo', 'ceo')`);
        await queryRunner.query(`CREATE TYPE "public"."expense_approvals_status_enum" AS ENUM('pending', 'approved', 'rejected', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "expense_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "approvalLevel" "public"."expense_approvals_approvallevel_enum" NOT NULL, "status" "public"."expense_approvals_status_enum" NOT NULL DEFAULT 'pending', "approvedAmount" numeric(12,2), "comments" text, "approvedDate" date, "sequence" integer NOT NULL DEFAULT '1', "isRequired" boolean NOT NULL DEFAULT false, "minimumAmount" numeric(12,2), "maximumAmount" numeric(12,2), "expense_id" uuid, "approver_id" uuid, "assigned_to" uuid, CONSTRAINT "PK_01be3ec916c6a30688988952003" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8e54d69943c0a15adce1ac3ab" ON "expense_approvals" ("approvalLevel") `);
        await queryRunner.query(`CREATE INDEX "IDX_31743d2d28c0edce572d797c49" ON "expense_approvals" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."expense_attachments_type_enum" AS ENUM('receipt', 'invoice', 'proof_of_payment', 'contract', 'photo', 'document', 'other')`);
        await queryRunner.query(`CREATE TABLE "expense_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "fileName" character varying(255) NOT NULL, "originalName" character varying(255) NOT NULL, "filePath" text NOT NULL, "mimeType" character varying(100) NOT NULL, "fileSize" bigint NOT NULL, "type" "public"."expense_attachments_type_enum" NOT NULL, "description" text, "metadata" json, "expense_id" uuid, CONSTRAINT "PK_0baa50797b094b065d0f53df89d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_type_enum" AS ENUM('operational', 'administrative', 'marketing', 'travel', 'meals', 'office_supplies', 'utilities', 'rent', 'insurance', 'professional_services', 'equipment', 'maintenance', 'transportation', 'communication', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('fixed_cost', 'variable_cost', 'semi_variable', 'direct_cost', 'indirect_cost')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('draft', 'submitted', 'pending_approval', 'approved', 'rejected', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_paymentmethod_enum" AS ENUM('cash', 'credit_card', 'debit_card', 'bank_transfer', 'check', 'mobile_payment', 'petty_cash')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_recurrence_enum" AS ENUM('one_time', 'daily', 'weekly', 'monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "expenseNumber" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "type" "public"."expenses_type_enum" NOT NULL, "category" "public"."expenses_category_enum" NOT NULL, "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'draft', "amount" numeric(12,2) NOT NULL, "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "taxAmount" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL, "expenseDate" date NOT NULL, "dueDate" date, "paymentMethod" "public"."expenses_paymentmethod_enum" NOT NULL, "vendor" character varying(255), "receiptNumber" character varying(100), "referenceNumber" character varying(100), "notes" text, "recurrence" "public"."expenses_recurrence_enum" NOT NULL DEFAULT 'one_time', "isReimbursable" boolean NOT NULL DEFAULT false, "isReimbursed" boolean NOT NULL DEFAULT false, "reimbursedDate" date, "isTaxDeductible" boolean NOT NULL DEFAULT true, "approvedAmount" numeric(12,2) NOT NULL DEFAULT '0', "rejectionReason" text, "costCenter" character varying(100), "project" character varying(100), "department" character varying(100), "metadata" json, "submitted_by" uuid, "company_id" uuid, "branch_id" uuid, CONSTRAINT "UQ_57552c177da550b3271a2cfb646" UNIQUE ("expenseNumber"), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e069bf5f4d4aaab62a84f24ca4" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d9547156ad50bae6149482e52" ON "expenses" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f52fb01c27607bb74ba05abf16" ON "expenses" ("expenseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_c74428bcafedde6850cdacaf0a" ON "expenses" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_57552c177da550b3271a2cfb64" ON "expenses" ("expenseNumber") `);
        await queryRunner.query(`ALTER TABLE "customers" ADD "creditLimit" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "currentCreditBalance" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "availableCredit" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."customers_creditrating_enum" AS ENUM('excellent', 'good', 'fair', 'poor', 'no_rating')`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "creditRating" "public"."customers_creditrating_enum" NOT NULL DEFAULT 'no_rating'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "paymentTermsDays" integer NOT NULL DEFAULT '30'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "isCreditApproved" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "creditApprovedDate" date`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "interestRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "allowCreditSales" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "creditNotes" text`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7d071f4860956ae316fadf52e69" FOREIGN KEY ("credit_sales_id") REFERENCES "credit_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_sales" ADD CONSTRAINT "FK_410784f6bf63eb82bb0face8e34" FOREIGN KEY ("sales_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_sales" ADD CONSTRAINT "FK_185fc43987211510509d599e66f" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_sales" ADD CONSTRAINT "FK_ce87faefde2c05a11e666f28a0d" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_121744c3063cfae889a37384fe4" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_e72e88d348ffb035d125408a546" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_42ac2fef6580d3b369845e2a5b8" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_f76f7eb70da05acd4e2be3403d4" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_caed0f51e45442af8cea5c410b2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" ADD CONSTRAINT "FK_a30df94c68e018e3854472c58a1" FOREIGN KEY ("receiving_id") REFERENCES "purchase_receivings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" ADD CONSTRAINT "FK_4318bdf33d315c84b608f336aad" FOREIGN KEY ("purchase_item_id") REFERENCES "purchase_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" ADD CONSTRAINT "FK_ce78e50ad2ef0237ec5debfb5fc" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_c430418f27a90fb62dedf135e38" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_46166001a69d40503f6b9dbf9a4" FOREIGN KEY ("received_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_0c7a111f7762b267a86d5814ed5" FOREIGN KEY ("quality_checked_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_77fc075133f1d2431822e630c14" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" ADD CONSTRAINT "FK_d6c21b14a308a4bd945743fb8d6" FOREIGN KEY ("expense_id") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" ADD CONSTRAINT "FK_0809d66cf62ff6396d7c10fe243" FOREIGN KEY ("approver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" ADD CONSTRAINT "FK_6d7084dd6a11edb3b2af62745f9" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_attachments" ADD CONSTRAINT "FK_e946f1f2ffdb088d00d21666a72" FOREIGN KEY ("expense_id") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_035cfd2ca0aea5567b55e114f9e" FOREIGN KEY ("submitted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_85389c627f20798554ac2bfb052" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_866a3b82ff438efc19c2398cda6" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_866a3b82ff438efc19c2398cda6"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_85389c627f20798554ac2bfb052"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_035cfd2ca0aea5567b55e114f9e"`);
        await queryRunner.query(`ALTER TABLE "expense_attachments" DROP CONSTRAINT "FK_e946f1f2ffdb088d00d21666a72"`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" DROP CONSTRAINT "FK_6d7084dd6a11edb3b2af62745f9"`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" DROP CONSTRAINT "FK_0809d66cf62ff6396d7c10fe243"`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" DROP CONSTRAINT "FK_d6c21b14a308a4bd945743fb8d6"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_77fc075133f1d2431822e630c14"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_0c7a111f7762b267a86d5814ed5"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_46166001a69d40503f6b9dbf9a4"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_c430418f27a90fb62dedf135e38"`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" DROP CONSTRAINT "FK_ce78e50ad2ef0237ec5debfb5fc"`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" DROP CONSTRAINT "FK_4318bdf33d315c84b608f336aad"`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" DROP CONSTRAINT "FK_a30df94c68e018e3854472c58a1"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_caed0f51e45442af8cea5c410b2"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_f76f7eb70da05acd4e2be3403d4"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_42ac2fef6580d3b369845e2a5b8"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_e72e88d348ffb035d125408a546"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_121744c3063cfae889a37384fe4"`);
        await queryRunner.query(`ALTER TABLE "credit_sales" DROP CONSTRAINT "FK_ce87faefde2c05a11e666f28a0d"`);
        await queryRunner.query(`ALTER TABLE "credit_sales" DROP CONSTRAINT "FK_185fc43987211510509d599e66f"`);
        await queryRunner.query(`ALTER TABLE "credit_sales" DROP CONSTRAINT "FK_410784f6bf63eb82bb0face8e34"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7d071f4860956ae316fadf52e69"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "creditNotes"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "allowCreditSales"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "interestRate"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "creditApprovedDate"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "isCreditApproved"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "paymentTermsDays"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "creditRating"`);
        await queryRunner.query(`DROP TYPE "public"."customers_creditrating_enum"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "availableCredit"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "currentCreditBalance"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "creditLimit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57552c177da550b3271a2cfb64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74428bcafedde6850cdacaf0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52fb01c27607bb74ba05abf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d9547156ad50bae6149482e52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e069bf5f4d4aaab62a84f24ca4"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_recurrence_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_type_enum"`);
        await queryRunner.query(`DROP TABLE "expense_attachments"`);
        await queryRunner.query(`DROP TYPE "public"."expense_attachments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31743d2d28c0edce572d797c49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8e54d69943c0a15adce1ac3ab"`);
        await queryRunner.query(`DROP TABLE "expense_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."expense_approvals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expense_approvals_approvallevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65b827b253a3e00953c2f572d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_289617b91e6c6f79acf5ef3f11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4628685050edbefe5a1e7e96aa"`);
        await queryRunner.query(`DROP TABLE "purchase_receivings"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_receivings_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_receiving_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e0fc7a6605393a9bd691cdceb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5272ac3aa931eedb14cd8789d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8be43e7dd0ae89d236418c690c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3253914487a9fa14a59831dba9"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_approvalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_purchasetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca7fd8e07266825408bced5e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c24beb35bae25c17c4ef994"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6e01fc2d8cf385bfc153d1564"`);
        await queryRunner.query(`DROP TABLE "purchase_payments"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a8c41174bc84bc88ad449d782"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fd1a880e6b7f5a0aebfdd0fd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13f726be006367743fa6f4b995"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59639f22c81a78f565317397d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a4e583956e8fdaec7509bdf00"`);
        await queryRunner.query(`DROP TABLE "credit_sales"`);
        await queryRunner.query(`DROP TYPE "public"."credit_sales_creditterms_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credit_sales_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d8df244a3285386e0e7ff4877"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecce1591ffad0b35998e629071"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe3afb7bec2966c3957bbed52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2205fee5ec7c833f542ca0bfd9"`);
        await queryRunner.query(`DROP TABLE "credit_payments"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymentmethod_enum"`);
    }

}
