import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCreditModule1757261680701 implements MigrationInterface {
    name = 'AddCreditModule1757261680701'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7d071f4860956ae316fadf52e69"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2205fee5ec7c833f542ca0bfd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe3afb7bec2966c3957bbed52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_phone_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_transactions_type_enum" AS ENUM('credit_issued', 'payment_received', 'payment_made', 'interest_applied', 'late_fee_applied', 'adjustment', 'write_off')`);
        await queryRunner.query(`CREATE TABLE "credit_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "transactionNumber" character varying(50) NOT NULL, "type" "public"."credit_transactions_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "balanceAfter" numeric(12,2) NOT NULL, "transactionDate" date NOT NULL, "description" text, "referenceId" character varying(100), "metadata" json, "creditId" uuid NOT NULL, "processedById" uuid NOT NULL, CONSTRAINT "UQ_b87fa3cdbeacdfdb702e5f6dc4d" UNIQUE ("transactionNumber"), CONSTRAINT "PK_a408319811d1ab32832ec86fc2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22b90d46370278846f0ef9f23f" ON "credit_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad93c8877579638af537171bf0" ON "credit_transactions" ("transactionDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccae053f04966cbfb1425f26ca" ON "credit_transactions" ("creditId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b87fa3cdbeacdfdb702e5f6dc4" ON "credit_transactions" ("transactionNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."credits_type_enum" AS ENUM('receivable', 'payable', 'loan', 'advance')`);
        await queryRunner.query(`CREATE TYPE "public"."credits_status_enum" AS ENUM('pending', 'approved', 'active', 'partially_paid', 'fully_paid', 'overdue', 'written_off', 'cancelled', 'disputed')`);
        await queryRunner.query(`CREATE TYPE "public"."credits_creditrating_enum" AS ENUM('excellent', 'good', 'fair', 'poor', 'no_rating')`);
        await queryRunner.query(`CREATE TABLE "credits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "creditNumber" character varying(50) NOT NULL, "type" "public"."credits_type_enum" NOT NULL, "status" "public"."credits_status_enum" NOT NULL DEFAULT 'pending', "principalAmount" numeric(12,2) NOT NULL, "interestAmount" numeric(12,2) NOT NULL DEFAULT '0', "feesAmount" numeric(12,2) NOT NULL DEFAULT '0', "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "remainingBalance" numeric(12,2) NOT NULL DEFAULT '0', "interestRate" numeric(5,2) NOT NULL DEFAULT '0', "issueDate" date NOT NULL, "dueDate" date NOT NULL, "paymentTermsDays" integer NOT NULL DEFAULT '30', "creditRating" "public"."credits_creditrating_enum" NOT NULL DEFAULT 'no_rating', "description" text, "terms" text, "notes" text, "isDisputed" boolean NOT NULL DEFAULT false, "disputeReason" text, "lastReminderSent" date, "reminderCount" integer NOT NULL DEFAULT '0', "metadata" json, "companyId" uuid NOT NULL, "customerId" uuid, "createdById" uuid NOT NULL, "approvedById" uuid, "approvedDate" date, CONSTRAINT "UQ_f7ad288fcf48c8e2faeaa5ab283" UNIQUE ("creditNumber"), CONSTRAINT "PK_45cea097fd0ee625d2e840ed99c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63eb2147c6929d75882ce4738e" ON "credits" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_456c18cb444e722f0b86840868" ON "credits" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_82ccf8ec4ff6e01df1a2b1e97b" ON "credits" ("companyId", "type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f7ad288fcf48c8e2faeaa5ab28" ON "credits" ("creditNumber") `);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "isReconciled"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciledDate"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToPrincipal"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToInterest"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToFees"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "credit_sales_id"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processed_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciled_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentType"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "checkNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "bankAccount"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        // First, get the first company ID to use as default
        const firstCompany = await queryRunner.query(`SELECT id FROM companies LIMIT 1`);
        const defaultCompanyId = firstCompany[0]?.id;

        if (!defaultCompanyId) {
            throw new Error('No companies found. Please create a company first.');
        }

        // Add columns as nullable first
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid`);
        
        // Update existing records with NULL values
        await queryRunner.query(`UPDATE branches SET "companyId" = $1 WHERE "companyId" IS NULL`, [defaultCompanyId]);
        await queryRunner.query(`UPDATE suppliers SET "companyId" = $1 WHERE "companyId" IS NULL`, [defaultCompanyId]);
        
        // Now make them NOT NULL
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "companyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "companyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "principalAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "interestAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "feesAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "transactionReference" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "creditId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processedById" uuid NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymenttype_enum" AS ENUM('payment', 'partial_payment', 'overpayment', 'refund', 'adjustment', 'write_off')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentType" "public"."credit_payments_paymenttype_enum" NOT NULL DEFAULT 'payment'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "checkNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "bankAccount" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentDetails" json`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "isReconciled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciledDate" date`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToPrincipal" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToInterest" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToFees" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "credit_sales_id" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciled_by" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum" RENAME TO "suppliers_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('active', 'inactive', 'blacklisted', 'pending_approval', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum" USING "status"::"text"::"public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."credit_payments_status_enum" RENAME TO "credit_payments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" TYPE "public"."credit_payments_status_enum" USING "status"::"text"::"public"."credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" "public"."credit_payments_paymentmethod_enum" NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5be5e14c7b17f53289a0289981" ON "credit_payments" ("creditId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2205fee5ec7c833f542ca0bfd9" ON "credit_payments" ("paymentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe3afb7bec2966c3957bbed52" ON "credit_payments" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bdf3ec1f33c40450a9cf49b79d" ON "customers" ("phoneNumber", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_5be5e14c7b17f53289a02899811" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_607224eff620e73a84b9519155e" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" ADD CONSTRAINT "FK_ccae053f04966cbfb1425f26ca7" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" ADD CONSTRAINT "FK_065eee9c3053c4f52f7bc0d996c" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_4b584773f9c412d6eec7b45539c" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_4c00a69bfdcc1daa12fabeeb0ea" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_3176a2c3cfdfc3e52a7ef2be382" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_d1adbadda7e5a8acef6f7857b69" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7d071f4860956ae316fadf52e69" FOREIGN KEY ("credit_sales_id") REFERENCES "credit_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7d071f4860956ae316fadf52e69"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_d1adbadda7e5a8acef6f7857b69"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_3176a2c3cfdfc3e52a7ef2be382"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_4c00a69bfdcc1daa12fabeeb0ea"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_4b584773f9c412d6eec7b45539c"`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" DROP CONSTRAINT "FK_065eee9c3053c4f52f7bc0d996c"`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" DROP CONSTRAINT "FK_ccae053f04966cbfb1425f26ca7"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_607224eff620e73a84b9519155e"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_5be5e14c7b17f53289a02899811"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdf3ec1f33c40450a9cf49b79d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe3afb7bec2966c3957bbed52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2205fee5ec7c833f542ca0bfd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5be5e14c7b17f53289a0289981"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" "public"."credit_payments_paymentmethod_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum_old" AS ENUM('pending', 'completed', 'failed', 'cancelled', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" TYPE "public"."credit_payments_status_enum_old" USING "status"::"text"::"public"."credit_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."credit_payments_status_enum_old" RENAME TO "credit_payments_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum_old" AS ENUM('active', 'inactive', 'blacklisted')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum_old" USING "status"::"text"::"public"."suppliers_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum_old" RENAME TO "suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciled_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processed_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "credit_sales_id"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToFees"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToInterest"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToPrincipal"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciledDate"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "isReconciled"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "bankAccount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "checkNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentType"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processedById"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "creditId"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "transactionReference"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "feesAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "interestAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "principalAmount"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "bankAccount" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "checkNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymenttype_enum" AS ENUM('payment', 'partial_payment', 'overpayment', 'refund', 'adjustment', 'write_off')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentType" "public"."credit_payments_paymenttype_enum" NOT NULL DEFAULT 'payment'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciled_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "credit_sales_id" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToFees" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToInterest" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToPrincipal" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciledDate" date`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "isReconciled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentDetails" json`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7ad288fcf48c8e2faeaa5ab28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82ccf8ec4ff6e01df1a2b1e97b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_456c18cb444e722f0b86840868"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63eb2147c6929d75882ce4738e"`);
        await queryRunner.query(`DROP TABLE "credits"`);
        await queryRunner.query(`DROP TYPE "public"."credits_creditrating_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credits_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credits_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b87fa3cdbeacdfdb702e5f6dc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccae053f04966cbfb1425f26ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad93c8877579638af537171bf0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22b90d46370278846f0ef9f23f"`);
        await queryRunner.query(`DROP TABLE "credit_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."credit_transactions_type_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE (email IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_customer_phone_company" ON "customers" ("phoneNumber", "companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe3afb7bec2966c3957bbed52" ON "credit_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2205fee5ec7c833f542ca0bfd9" ON "credit_payments" ("paymentType") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE (email IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7d071f4860956ae316fadf52e69" FOREIGN KEY ("credit_sales_id") REFERENCES "credit_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
