import { MigrationInterface, QueryRunner } from "typeorm";

export class AddFilesModuleFixed1758026605067 implements MigrationInterface {
    name = 'AddFilesModuleFixed1758026605067'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7d071f4860956ae316fadf52e69"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_5be5e14c7b17f53289a02899811"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_607224eff620e73a84b9519155e"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2205fee5ec7c833f542ca0bfd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe3afb7bec2966c3957bbed52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5be5e14c7b17f53289a0289981"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`CREATE TYPE "public"."files_filetype_enum" AS ENUM('image', 'pdf', 'document', 'video', 'audio', 'archive', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."files_status_enum" AS ENUM('active', 'inactive', 'processing', 'deleted', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."files_storagetype_enum" AS ENUM('local', 's3', 'minio', 'google_cloud', 'azure')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "originalName" character varying(255) NOT NULL, "fileName" character varying(255) NOT NULL, "filePath" character varying(500) NOT NULL, "mimeType" character varying(100) NOT NULL, "size" bigint NOT NULL, "fileType" "public"."files_filetype_enum" NOT NULL, "status" "public"."files_status_enum" NOT NULL DEFAULT 'active', "storageType" "public"."files_storagetype_enum" NOT NULL DEFAULT 'local', "url" character varying(500), "thumbnailPath" character varying(500), "thumbnailUrl" character varying(500), "entityId" uuid, "entityType" character varying(100), "description" text, "alt" text, "metadata" json, "checksum" character varying(64), "companyId" uuid, "uploadedById" uuid NOT NULL, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_866212928289ec1112edd04ebf" ON "files" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a08866dd8bfcf715da55a567ae" ON "files" ("fileType") `);
        await queryRunner.query(`CREATE INDEX "IDX_20c2e6aeb3fe09613808ba1eab" ON "files" ("entityId", "entityType") `);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentType"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "isReconciled"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciledDate"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToPrincipal"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToInterest"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToFees"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "credit_sales_id"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processed_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciled_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "checkNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "bankAccount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "principalAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "interestAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "feesAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "creditId"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processedById"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "transactionReference"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        // Get first company ID to use as default for existing records
        const companies = await queryRunner.query(`SELECT id FROM companies LIMIT 1`);
        const defaultCompanyId = companies.length > 0 ? companies[0].id : null;
        
        // Add columns as nullable first
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid`);
        
        // Update existing records if we have a default company
        if (defaultCompanyId) {
            await queryRunner.query(`UPDATE "branches" SET "companyId" = $1 WHERE "companyId" IS NULL`, [defaultCompanyId]);
            await queryRunner.query(`UPDATE "suppliers" SET "companyId" = $1 WHERE "companyId" IS NULL`, [defaultCompanyId]);
        }
        
        // Make companyId NOT NULL only if we have data
        if (defaultCompanyId) {
            await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "companyId" SET NOT NULL`);
            await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "companyId" SET NOT NULL`);
        }
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "principalAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "interestAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "feesAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "transactionReference" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "creditId" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processedById" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymenttype_enum" AS ENUM('payment', 'partial_payment', 'overpayment', 'refund', 'adjustment', 'write_off')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentType" "public"."credit_payments_paymenttype_enum" NOT NULL DEFAULT 'payment'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "checkNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "bankAccount" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentDetails" json`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "isReconciled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciledDate" date`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToPrincipal" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToInterest" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToFees" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "credit_sales_id" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciled_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymentmethod_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" "public"."credit_payments_paymentmethod_enum" NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."credit_payments_status_enum" RENAME TO "credit_payments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" TYPE "public"."credit_payments_status_enum" USING "status"::"text"::"public"."credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum" RENAME TO "suppliers_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('active', 'inactive', 'blacklisted')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum" USING "status"::"text"::"public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5be5e14c7b17f53289a0289981" ON "credit_payments" ("creditId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2205fee5ec7c833f542ca0bfd9" ON "credit_payments" ("paymentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe3afb7bec2966c3957bbed52" ON "credit_payments" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_5be5e14c7b17f53289a02899811" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_607224eff620e73a84b9519155e" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7d071f4860956ae316fadf52e69" FOREIGN KEY ("credit_sales_id") REFERENCES "credit_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a525d85f0ac59aa9a971825e1af" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a330ae0dd450f91c6b9c7fda688" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a330ae0dd450f91c6b9c7fda688"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a525d85f0ac59aa9a971825e1af"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7d071f4860956ae316fadf52e69"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_607224eff620e73a84b9519155e"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_5be5e14c7b17f53289a02899811"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe3afb7bec2966c3957bbed52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2205fee5ec7c833f542ca0bfd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5be5e14c7b17f53289a0289981"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum_old" AS ENUM('active', 'inactive', 'blacklisted', 'pending_approval', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum_old" USING "status"::"text"::"public"."suppliers_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum_old" RENAME TO "suppliers_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum_old" AS ENUM('pending', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" TYPE "public"."credit_payments_status_enum_old" USING "status"::"text"::"public"."credit_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."credit_payments_status_enum_old" RENAME TO "credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" "public"."credit_payments_paymentmethod_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciled_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processed_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "credit_sales_id"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToFees"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToInterest"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToPrincipal"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciledDate"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "isReconciled"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "bankAccount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "checkNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentType"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processedById"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "creditId"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "transactionReference"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "feesAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "interestAmount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "principalAmount"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "transactionReference" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processedById" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "creditId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "feesAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "interestAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "principalAmount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "bankAccount" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "checkNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciled_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "credit_sales_id" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToFees" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToInterest" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToPrincipal" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciledDate" date`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "isReconciled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentDetails" json`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymenttype_enum" AS ENUM('payment', 'partial_payment', 'overpayment', 'refund', 'adjustment', 'write_off')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentType" "public"."credit_payments_paymenttype_enum" NOT NULL DEFAULT 'payment'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20c2e6aeb3fe09613808ba1eab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a08866dd8bfcf715da55a567ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866212928289ec1112edd04ebf"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_storagetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."files_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."files_filetype_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE (email IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5be5e14c7b17f53289a0289981" ON "credit_payments" ("creditId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe3afb7bec2966c3957bbed52" ON "credit_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2205fee5ec7c833f542ca0bfd9" ON "credit_payments" ("paymentType") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE (email IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_607224eff620e73a84b9519155e" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_5be5e14c7b17f53289a02899811" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7d071f4860956ae316fadf52e69" FOREIGN KEY ("credit_sales_id") REFERENCES "credit_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
