import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTransferEntities1758566335274 implements MigrationInterface {
    name = 'AddTransferEntities1758566335274'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7d071f4860956ae316fadf52e69"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2205fee5ec7c833f542ca0bfd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe3afb7bec2966c3957bbed52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`CREATE TABLE "transfer_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL, "notes" text, "transferId" uuid NOT NULL, "productId" uuid NOT NULL, CONSTRAINT "PK_d7258a0518246eabb01bffd56a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transfers_type_enum" AS ENUM('warehouse_to_warehouse', 'warehouse_to_shop', 'shop_to_warehouse', 'shop_to_shop')`);
        await queryRunner.query(`CREATE TYPE "public"."transfers_status_enum" AS ENUM('pending', 'in_transit', 'completed', 'cancelled', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "transferNumber" character varying(50) NOT NULL, "type" "public"."transfers_type_enum" NOT NULL, "status" "public"."transfers_status_enum" NOT NULL DEFAULT 'pending', "sourceWarehouseId" uuid, "sourceShopId" uuid, "destinationWarehouseId" uuid, "destinationShopId" uuid, "notes" text, "rejectionReason" text, "expectedDate" TIMESTAMP, "completedDate" TIMESTAMP, "createdById" uuid NOT NULL, "approvedById" uuid, "metadata" json, CONSTRAINT "UQ_0333218b127ac6dbb3f7eac3bff" UNIQUE ("transferNumber"), CONSTRAINT "PK_f712e908b465e0085b4408cabc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad83f9fa2b36ccd2893b10a390" ON "transfers" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6148a86991f8e5fd92d6b9c684" ON "transfers" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a74701d10eb1b73b47f1d38af" ON "transfers" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0333218b127ac6dbb3f7eac3bf" ON "transfers" ("transferNumber") `);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentType"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "isReconciled"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciledDate"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToPrincipal"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToInterest"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "appliedToFees"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "credit_sales_id"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "processed_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "reconciled_by"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "bankAccount"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "checkNumber"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum" RENAME TO "suppliers_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('active', 'inactive', 'blacklisted', 'pending_approval', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum" USING "status"::"text"::"public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_5be5e14c7b17f53289a02899811"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_607224eff620e73a84b9519155e"`);
        await queryRunner.query(`ALTER TYPE "public"."credit_payments_status_enum" RENAME TO "credit_payments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" TYPE "public"."credit_payments_status_enum" USING "status"::"text"::"public"."credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "creditId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "processedById" SET NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_5be5e14c7b17f53289a02899811" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_607224eff620e73a84b9519155e" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_items" ADD CONSTRAINT "FK_68c98df7d513511ac09e26ca9c3" FOREIGN KEY ("transferId") REFERENCES "transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_items" ADD CONSTRAINT "FK_05045a77e7c8c080ce93cffc547" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_8c8f4def51a0411f95b1b4c8016" FOREIGN KEY ("sourceWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_0713446954e2d4b81c831f215b6" FOREIGN KEY ("sourceShopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_f9911ee7d284f6d7eaaacb92547" FOREIGN KEY ("destinationWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_02f4cb11e0d1e982682b269c1f5" FOREIGN KEY ("destinationShopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_9ed2455b82163fa753259d41301" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_bea0014a61ad163994ef7827134" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_bea0014a61ad163994ef7827134"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_9ed2455b82163fa753259d41301"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_02f4cb11e0d1e982682b269c1f5"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_f9911ee7d284f6d7eaaacb92547"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_0713446954e2d4b81c831f215b6"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_8c8f4def51a0411f95b1b4c8016"`);
        await queryRunner.query(`ALTER TABLE "transfer_items" DROP CONSTRAINT "FK_05045a77e7c8c080ce93cffc547"`);
        await queryRunner.query(`ALTER TABLE "transfer_items" DROP CONSTRAINT "FK_68c98df7d513511ac09e26ca9c3"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_607224eff620e73a84b9519155e"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_5be5e14c7b17f53289a02899811"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "processedById" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "creditId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymentmethod_enum" AS ENUM('bank_transfer', 'cash', 'cheque', 'credit', 'cryptocurrency', 'debit', 'mobile_money', 'online')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentMethod" "public"."credit_payments_paymentmethod_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum_old" AS ENUM('cancelled', 'completed', 'failed', 'pending', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" TYPE "public"."credit_payments_status_enum_old" USING "status"::"text"::"public"."credit_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."credit_payments_status_enum_old" RENAME TO "credit_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_607224eff620e73a84b9519155e" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_5be5e14c7b17f53289a02899811" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum_old" AS ENUM('active', 'blacklisted', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum_old" USING "status"::"text"::"public"."suppliers_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum_old" RENAME TO "suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "checkNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "bankAccount" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciled_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "processed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "credit_sales_id" uuid`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToFees" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToInterest" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "appliedToPrincipal" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "reconciledDate" date`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "isReconciled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentDetails" json`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_paymenttype_enum" AS ENUM('adjustment', 'overpayment', 'partial_payment', 'payment', 'refund', 'write_off')`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD "paymentType" "public"."credit_payments_paymenttype_enum" NOT NULL DEFAULT 'payment'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0333218b127ac6dbb3f7eac3bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a74701d10eb1b73b47f1d38af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6148a86991f8e5fd92d6b9c684"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad83f9fa2b36ccd2893b10a390"`);
        await queryRunner.query(`DROP TABLE "transfers"`);
        await queryRunner.query(`DROP TYPE "public"."transfers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transfers_type_enum"`);
        await queryRunner.query(`DROP TABLE "transfer_items"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE (email IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe3afb7bec2966c3957bbed52" ON "credit_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2205fee5ec7c833f542ca0bfd9" ON "credit_payments" ("paymentType") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE (email IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7b84c783bfefa94c1d865b1b5c5" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_d2286e2451e1d9c536962ea0a4c" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_7d071f4860956ae316fadf52e69" FOREIGN KEY ("credit_sales_id") REFERENCES "credit_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
