import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1760176395417 implements MigrationInterface {
    name = 'Migrations1760176395417'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "branches_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "companies_createdBy_fkey"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "shops_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "shops_warehouseId_fkey"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "shops_ownerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "employees_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "employees_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_shopId_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_warehouseId_fkey"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "customers_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_createdById_fkey"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "warehouses_managerId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customers_phone_company"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('active', 'inactive', 'blacklisted', 'pending_approval', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "contact" character varying(20) NOT NULL, "email" character varying(255), "address" character varying(255), "contactPerson" character varying(255), "taxNumber" character varying(100), "description" text, "status" "public"."suppliers_status_enum" NOT NULL DEFAULT 'active', "creditLimit" numeric(10,2) NOT NULL DEFAULT '0', "paymentTermsDays" integer NOT NULL DEFAULT '30', "bankDetails" json, "emergencyContact" json, "metadata" json, "companyId" uuid, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c1a78b27ce1426491f175e034" ON "suppliers" ("email", "companyId") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f92bfee8f136fab50cc3feb7" ON "suppliers" ("name", "companyId") `);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "credit_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "paymentNumber" character varying(50) NOT NULL, "amount" numeric(12,2) NOT NULL, "principalAmount" numeric(12,2) NOT NULL DEFAULT '0', "interestAmount" numeric(12,2) NOT NULL DEFAULT '0', "feesAmount" numeric(12,2) NOT NULL DEFAULT '0', "paymentDate" date NOT NULL, "status" "public"."credit_payments_status_enum" NOT NULL DEFAULT 'pending', "paymentMethod" character varying(50) NOT NULL, "transactionReference" character varying(100), "notes" text, "metadata" json, "creditId" uuid NOT NULL, "processedById" uuid NOT NULL, CONSTRAINT "UQ_7d8df244a3285386e0e7ff4877d" UNIQUE ("paymentNumber"), CONSTRAINT "PK_c8bf096041d9d988603b649ee33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecce1591ffad0b35998e629071" ON "credit_payments" ("paymentDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_5be5e14c7b17f53289a0289981" ON "credit_payments" ("creditId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7d8df244a3285386e0e7ff4877" ON "credit_payments" ("paymentNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."credit_transactions_type_enum" AS ENUM('credit_issued', 'payment_received', 'payment_made', 'interest_applied', 'late_fee_applied', 'adjustment', 'write_off')`);
        await queryRunner.query(`CREATE TABLE "credit_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "transactionNumber" character varying(50) NOT NULL, "type" "public"."credit_transactions_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "balanceAfter" numeric(12,2) NOT NULL, "transactionDate" date NOT NULL, "description" text, "referenceId" character varying(100), "metadata" json, "creditId" uuid NOT NULL, "processedById" uuid NOT NULL, CONSTRAINT "UQ_b87fa3cdbeacdfdb702e5f6dc4d" UNIQUE ("transactionNumber"), CONSTRAINT "PK_a408319811d1ab32832ec86fc2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22b90d46370278846f0ef9f23f" ON "credit_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad93c8877579638af537171bf0" ON "credit_transactions" ("transactionDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccae053f04966cbfb1425f26ca" ON "credit_transactions" ("creditId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b87fa3cdbeacdfdb702e5f6dc4" ON "credit_transactions" ("transactionNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."credits_type_enum" AS ENUM('receivable', 'payable', 'loan', 'advance')`);
        await queryRunner.query(`CREATE TYPE "public"."credits_status_enum" AS ENUM('pending', 'approved', 'active', 'partially_paid', 'fully_paid', 'overdue', 'written_off', 'cancelled', 'disputed')`);
        await queryRunner.query(`CREATE TYPE "public"."credits_creditrating_enum" AS ENUM('excellent', 'good', 'fair', 'poor', 'no_rating')`);
        await queryRunner.query(`CREATE TABLE "credits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "creditNumber" character varying(50) NOT NULL, "type" "public"."credits_type_enum" NOT NULL, "status" "public"."credits_status_enum" NOT NULL DEFAULT 'pending', "principalAmount" numeric(12,2) NOT NULL, "interestAmount" numeric(12,2) NOT NULL DEFAULT '0', "feesAmount" numeric(12,2) NOT NULL DEFAULT '0', "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "remainingBalance" numeric(12,2) NOT NULL DEFAULT '0', "interestRate" numeric(5,2) NOT NULL DEFAULT '0', "issueDate" date NOT NULL, "dueDate" date NOT NULL, "paymentTermsDays" integer NOT NULL DEFAULT '30', "creditRating" "public"."credits_creditrating_enum" NOT NULL DEFAULT 'no_rating', "description" text, "terms" text, "notes" text, "isDisputed" boolean NOT NULL DEFAULT false, "disputeReason" text, "lastReminderSent" date, "reminderCount" integer NOT NULL DEFAULT '0', "metadata" json, "companyId" uuid NOT NULL, "customerId" uuid, "createdById" uuid NOT NULL, "approvedById" uuid, "approvedDate" date, CONSTRAINT "UQ_f7ad288fcf48c8e2faeaa5ab283" UNIQUE ("creditNumber"), CONSTRAINT "PK_45cea097fd0ee625d2e840ed99c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63eb2147c6929d75882ce4738e" ON "credits" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_456c18cb444e722f0b86840868" ON "credits" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_82ccf8ec4ff6e01df1a2b1e97b" ON "credits" ("companyId", "type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f7ad288fcf48c8e2faeaa5ab28" ON "credits" ("creditNumber") `);
        await queryRunner.query(`CREATE TABLE "shop_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "stockQuantity" integer NOT NULL DEFAULT '0', "minStockLevel" integer NOT NULL DEFAULT '0', "salesQuantity" integer NOT NULL DEFAULT '0', "salesRevenue" numeric(10,2) NOT NULL DEFAULT '0', "lastSaleDate" date, "shopId" uuid, "productId" uuid, CONSTRAINT "UQ_51f059443ae0eb5eb6659d14f9a" UNIQUE ("shopId", "productId"), CONSTRAINT "PK_bc7b9a757fadb6a6b0e5cc4bf7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_type_enum" AS ENUM('percentage', 'fixed', 'bogo', 'bulk_discount')`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "description" text, "code" character varying(50), "type" "public"."discounts_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "minimumOrderAmount" numeric(10,2), "maximumDiscountAmount" numeric(10,2), "usageLimit" integer, "usageCount" integer NOT NULL DEFAULT '0', "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "applyToAllProducts" boolean NOT NULL DEFAULT false, "applyToAllCustomers" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_8c7cc2340e9ea0fc5a246e63749" UNIQUE ("code"), CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL, "unitPrice" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "subtotal" numeric(10,2) NOT NULL, "notes" text, "sales_id" uuid, "product_id" uuid, "discount_id" uuid, CONSTRAINT "PK_534cb3df276d77c81b1234c02b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_transactions_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_transactions_transactiontype_enum" AS ENUM('sale', 'return', 'refund', 'adjustment', 'transfer')`);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(10,2) NOT NULL, "paymentMethod" "public"."payment_transactions_paymentmethod_enum" NOT NULL, "transactionType" "public"."payment_transactions_transactiontype_enum" NOT NULL, "transactionReference" character varying(100), "notes" character varying(255), "transactionDate" TIMESTAMP NOT NULL DEFAULT now(), "paymentDetails" json, "isSuccessful" boolean NOT NULL DEFAULT true, "failureReason" character varying(255), "sale_id" uuid, "processed_by" uuid, CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_paymenttype_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('pending', 'completed', 'cancelled', 'refunded', 'partially_paid', 'returned', 'draft')`);
        await queryRunner.query(`CREATE TYPE "public"."sales_discounttype_enum" AS ENUM('percentage', 'fixed', 'bogo', 'bulk_discount')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "totalAmount" numeric(10,2) NOT NULL, "taxAmount" numeric(10,2) NOT NULL, "advancePayment" numeric(10,2) NOT NULL DEFAULT '0', "remainingBalance" numeric(10,2) NOT NULL DEFAULT '0', "saleDate" date NOT NULL, "paymentType" "public"."sales_paymenttype_enum" NOT NULL, "status" "public"."sales_status_enum" NOT NULL DEFAULT 'completed', "note" character varying(255), "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "discountType" "public"."sales_discounttype_enum", "discountRate" numeric(5,2) NOT NULL DEFAULT '0', "subtotal" numeric(10,2) NOT NULL, "invoiceNumber" character varying(50), "referenceNumber" character varying(100), "dueDate" date, "terms" text, "customerId" uuid, "warehouseId" uuid, "shop_id" uuid, "branch_id" uuid, "created_by" uuid, CONSTRAINT "UQ_4f4006dc362ea9cc6308b4fb23d" UNIQUE ("invoiceNumber"), CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(10,2) NOT NULL, "commissionDate" date NOT NULL, "commissionRate" numeric(10,2) NOT NULL, "commissionAmount" numeric(10,2) NOT NULL, "isApproved" boolean NOT NULL DEFAULT false, "approvedBy" uuid, "approvedAt" TIMESTAMP, "saleId" uuid, "productId" uuid, "employeeId" uuid, CONSTRAINT "PK_2701379966e2e670bb5ff0ae78e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transfers_type_enum" AS ENUM('warehouse_to_warehouse', 'warehouse_to_shop', 'shop_to_warehouse', 'shop_to_shop')`);
        await queryRunner.query(`CREATE TYPE "public"."transfers_status_enum" AS ENUM('pending', 'in_transit', 'completed', 'cancelled', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "transferNumber" character varying(50) NOT NULL, "type" "public"."transfers_type_enum" NOT NULL, "status" "public"."transfers_status_enum" NOT NULL DEFAULT 'pending', "sourceWarehouseId" uuid, "sourceShopId" uuid, "destinationWarehouseId" uuid, "destinationShopId" uuid, "notes" text, "rejectionReason" text, "expectedDate" TIMESTAMP, "completedDate" TIMESTAMP, "createdById" uuid NOT NULL, "approvedById" uuid, "metadata" json, CONSTRAINT "UQ_0333218b127ac6dbb3f7eac3bff" UNIQUE ("transferNumber"), CONSTRAINT "PK_f712e908b465e0085b4408cabc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad83f9fa2b36ccd2893b10a390" ON "transfers" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6148a86991f8e5fd92d6b9c684" ON "transfers" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a74701d10eb1b73b47f1d38af" ON "transfers" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0333218b127ac6dbb3f7eac3bf" ON "transfers" ("transferNumber") `);
        await queryRunner.query(`CREATE TABLE "transfer_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL, "notes" text, "transferId" uuid NOT NULL, "productId" uuid NOT NULL, CONSTRAINT "PK_d7258a0518246eabb01bffd56a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "featureAccess" jsonb NOT NULL DEFAULT '{}', "itemAttributeAccess" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "REL_bddba2e40b167c695b346b5ebd" UNIQUE ("userId"), CONSTRAINT "PK_e96f8a72909cf05817d9affb5cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."settings_measurementsystem_enum" AS ENUM('metric', 'imperial')`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "safetyStockThreshold" integer NOT NULL DEFAULT '5', "expiryReminderDays" integer NOT NULL DEFAULT '30', "enableLowStockNotifications" boolean NOT NULL DEFAULT true, "enableExpiryNotifications" boolean NOT NULL DEFAULT true, "autoReorderEnabled" boolean NOT NULL DEFAULT false, "defaultTaxRate" numeric(5,2) NOT NULL DEFAULT '0', "defaultCurrency" character varying(10) NOT NULL DEFAULT 'USD', "measurementSystem" "public"."settings_measurementsystem_enum" NOT NULL DEFAULT 'metric', "enableAuditLogs" boolean NOT NULL DEFAULT true, "auditLogRetentionDays" integer NOT NULL DEFAULT '365', "enableTwoFactorAuth" boolean NOT NULL DEFAULT false, "sessionTimeoutMinutes" integer NOT NULL DEFAULT '30', "enableCaching" boolean NOT NULL DEFAULT true, "cacheExpirationSeconds" integer NOT NULL DEFAULT '300', "enableEmailNotifications" boolean NOT NULL DEFAULT false, "enableSmsNotifications" boolean NOT NULL DEFAULT false, "companyName" character varying(255), "companyAddress" character varying(255), "companyPhone" character varying(20), "companyEmail" character varying(255), "companyLogo" text, "notificationSettings" json, "reportSettings" json, "integrationSettings" json, "customSettings" json, CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'view', 'login', 'logout', 'export', 'import')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "entityType" character varying(100) NOT NULL, "entityId" uuid, "action" "public"."audit_logs_action_enum" NOT NULL, "oldValues" json, "newValues" json, "description" character varying(255), "ipAddress" character varying(45), "userAgent" character varying(500), "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_items_status_enum" AS ENUM('pending', 'ordered', 'partially_received', 'fully_received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL, "receivedQuantity" integer NOT NULL DEFAULT '0', "rejectedQuantity" integer NOT NULL DEFAULT '0', "unitCost" numeric(10,2) NOT NULL, "actualUnitCost" numeric(10,2) NOT NULL DEFAULT '0', "totalCost" numeric(10,2) NOT NULL, "actualTotalCost" numeric(10,2) NOT NULL DEFAULT '0', "discountRate" numeric(5,2) NOT NULL DEFAULT '0', "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."purchase_items_status_enum" NOT NULL DEFAULT 'pending', "expectedDeliveryDate" date, "actualDeliveryDate" date, "notes" text, "specifications" text, "metadata" json, "qualityChecked" boolean NOT NULL DEFAULT false, "qualityApproved" boolean NOT NULL DEFAULT true, "qualityNotes" text, "purchase_order_id" uuid, "product_id" uuid, CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2a8c41174bc84bc88ad449d782" ON "purchase_items" ("purchase_order_id", "product_id") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_payments_paymentmethod_enum" AS ENUM('cash', 'credit', 'debit', 'online', 'bank_transfer', 'mobile_money', 'cheque', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "purchase_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(12,2) NOT NULL, "paymentMethod" "public"."purchase_payments_paymentmethod_enum" NOT NULL, "status" "public"."purchase_payments_status_enum" NOT NULL DEFAULT 'pending', "paymentDate" date NOT NULL, "referenceNumber" character varying(100), "checkNumber" character varying(100), "bankAccount" character varying(255), "notes" text, "paymentDetails" json, "isReconciled" boolean NOT NULL DEFAULT false, "reconciledDate" date, "transactionNumber" character varying(50) NOT NULL, "purchase_order_id" uuid, "processed_by" uuid, "reconciled_by" uuid, CONSTRAINT "UQ_9e3e268f416fbe648c8508cfd5f" UNIQUE ("transactionNumber"), CONSTRAINT "PK_9765d702e073d3cdf9b1600792d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6e01fc2d8cf385bfc153d1564" ON "purchase_payments" ("paymentMethod") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c24beb35bae25c17c4ef994" ON "purchase_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ca7fd8e07266825408bced5e1" ON "purchase_payments" ("paymentDate") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_purchasetype_enum" AS ENUM('stock_purchase', 'service_purchase', 'asset_purchase', 'supply_purchase')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'ordered', 'partially_received', 'fully_received', 'closed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_approvalstatus_enum" AS ENUM('pending', 'approved', 'rejected', 'auto_approved')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_paymentstatus_enum" AS ENUM('unpaid', 'partially_paid', 'fully_paid', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "poNumber" character varying(50) NOT NULL, "purchaseType" "public"."purchase_orders_purchasetype_enum" NOT NULL DEFAULT 'stock_purchase', "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "approvalStatus" "public"."purchase_orders_approvalstatus_enum" NOT NULL DEFAULT 'pending', "paymentStatus" "public"."purchase_orders_paymentstatus_enum" NOT NULL DEFAULT 'unpaid', "orderDate" date NOT NULL, "expectedDeliveryDate" date, "actualDeliveryDate" date, "dueDate" date, "subtotal" numeric(12,2) NOT NULL, "taxAmount" numeric(12,2) NOT NULL DEFAULT '0', "discountAmount" numeric(12,2) NOT NULL DEFAULT '0', "discountRate" numeric(5,2) NOT NULL DEFAULT '0', "shippingCost" numeric(12,2) NOT NULL DEFAULT '0', "otherCharges" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL, "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "remainingAmount" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "terms" text, "approvalNotes" text, "supplierInvoiceNumber" character varying(100), "referenceNumber" character varying(100), "paymentTermsDays" integer NOT NULL DEFAULT '30', "isUrgent" boolean NOT NULL DEFAULT false, "metadata" json, "supplier_id" uuid, "created_by" uuid, "approved_by" uuid, "warehouse_id" uuid, "branch_id" uuid, "company_id" uuid, CONSTRAINT "UQ_2e0fc7a6605393a9bd691cdcebe" UNIQUE ("poNumber"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3253914487a9fa14a59831dba9" ON "purchase_orders" ("expectedDeliveryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_8be43e7dd0ae89d236418c690c" ON "purchase_orders" ("orderDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_5272ac3aa931eedb14cd8789d6" ON "purchase_orders" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2e0fc7a6605393a9bd691cdceb" ON "purchase_orders" ("poNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_receivings_status_enum" AS ENUM('pending', 'partial', 'complete', 'over_received')`);
        await queryRunner.query(`CREATE TABLE "purchase_receivings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "receivingNumber" character varying(50) NOT NULL, "receivingDate" date NOT NULL, "status" "public"."purchase_receivings_status_enum" NOT NULL DEFAULT 'pending', "supplierDeliveryNote" character varying(100), "carrierName" character varying(100), "trackingNumber" character varying(100), "notes" text, "damageNotes" text, "hasDiscrepancies" boolean NOT NULL DEFAULT false, "discrepancyNotes" text, "qualityControlPassed" boolean NOT NULL DEFAULT false, "qualityControlNotes" text, "attachments" json, "metadata" json, "purchase_order_id" uuid, "received_by" uuid, "quality_checked_by" uuid, "warehouse_id" uuid, CONSTRAINT "UQ_65b827b253a3e00953c2f572d96" UNIQUE ("receivingNumber"), CONSTRAINT "PK_1c21b7e5fd38c6f6644e48a571d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4628685050edbefe5a1e7e96aa" ON "purchase_receivings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_289617b91e6c6f79acf5ef3f11" ON "purchase_receivings" ("receivingDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65b827b253a3e00953c2f572d9" ON "purchase_receivings" ("receivingNumber") `);
        await queryRunner.query(`CREATE TABLE "purchase_receiving_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "orderedQuantity" integer NOT NULL, "receivedQuantity" integer NOT NULL, "rejectedQuantity" integer NOT NULL DEFAULT '0', "unitCost" numeric(10,2) NOT NULL, "totalCost" numeric(10,2) NOT NULL, "notes" text, "rejectionReason" text, "qualityChecked" boolean NOT NULL DEFAULT false, "qualityApproved" boolean NOT NULL DEFAULT true, "qualityNotes" text, "expiryDate" date, "batchInfo" json, "metadata" json, "receiving_id" uuid, "purchase_item_id" uuid, "product_id" uuid, CONSTRAINT "PK_c7141c1486e84e89fc812a3d726" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."files_filetype_enum" AS ENUM('image', 'pdf', 'document', 'video', 'audio', 'archive', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."files_status_enum" AS ENUM('active', 'inactive', 'processing', 'deleted', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."files_storagetype_enum" AS ENUM('local', 's3', 'minio', 'google_cloud', 'azure')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "originalName" character varying(255) NOT NULL, "fileName" character varying(255) NOT NULL, "filePath" character varying(500) NOT NULL, "mimeType" character varying(100) NOT NULL, "size" bigint NOT NULL, "fileType" "public"."files_filetype_enum" NOT NULL, "status" "public"."files_status_enum" NOT NULL DEFAULT 'active', "storageType" "public"."files_storagetype_enum" NOT NULL DEFAULT 'local', "url" character varying(500), "thumbnailPath" character varying(500), "thumbnailUrl" character varying(500), "entityId" uuid, "entityType" character varying(100), "description" text, "alt" text, "metadata" json, "checksum" character varying(64), "companyId" uuid, "uploadedById" uuid NOT NULL, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_866212928289ec1112edd04ebf" ON "files" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a08866dd8bfcf715da55a567ae" ON "files" ("fileType") `);
        await queryRunner.query(`CREATE INDEX "IDX_20c2e6aeb3fe09613808ba1eab" ON "files" ("entityId", "entityType") `);
        await queryRunner.query(`CREATE TYPE "public"."expense_approvals_approvallevel_enum" AS ENUM('manager', 'senior_manager', 'finance_head', 'cfo', 'ceo')`);
        await queryRunner.query(`CREATE TYPE "public"."expense_approvals_status_enum" AS ENUM('pending', 'approved', 'rejected', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "expense_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "approvalLevel" "public"."expense_approvals_approvallevel_enum" NOT NULL, "status" "public"."expense_approvals_status_enum" NOT NULL DEFAULT 'pending', "approvedAmount" numeric(12,2), "comments" text, "approvedDate" date, "sequence" integer NOT NULL DEFAULT '1', "isRequired" boolean NOT NULL DEFAULT false, "minimumAmount" numeric(12,2), "maximumAmount" numeric(12,2), "expense_id" uuid, "approver_id" uuid, "assigned_to" uuid, CONSTRAINT "PK_01be3ec916c6a30688988952003" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8e54d69943c0a15adce1ac3ab" ON "expense_approvals" ("approvalLevel") `);
        await queryRunner.query(`CREATE INDEX "IDX_31743d2d28c0edce572d797c49" ON "expense_approvals" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."expense_attachments_type_enum" AS ENUM('receipt', 'invoice', 'proof_of_payment', 'contract', 'photo', 'document', 'other')`);
        await queryRunner.query(`CREATE TABLE "expense_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "fileName" character varying(255) NOT NULL, "originalName" character varying(255) NOT NULL, "filePath" text NOT NULL, "mimeType" character varying(100) NOT NULL, "fileSize" bigint NOT NULL, "type" "public"."expense_attachments_type_enum" NOT NULL, "description" text, "metadata" json, "expense_id" uuid, CONSTRAINT "PK_0baa50797b094b065d0f53df89d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_type_enum" AS ENUM('operational', 'administrative', 'marketing', 'travel', 'meals', 'office_supplies', 'utilities', 'rent', 'insurance', 'professional_services', 'equipment', 'maintenance', 'transportation', 'communication', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('fixed_cost', 'variable_cost', 'semi_variable', 'direct_cost', 'indirect_cost')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('draft', 'submitted', 'pending_approval', 'approved', 'rejected', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_paymentmethod_enum" AS ENUM('cash', 'credit_card', 'debit_card', 'bank_transfer', 'check', 'mobile_payment', 'petty_cash')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_recurrence_enum" AS ENUM('one_time', 'daily', 'weekly', 'monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "expenseNumber" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "type" "public"."expenses_type_enum" NOT NULL, "category" "public"."expenses_category_enum" NOT NULL, "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'draft', "amount" numeric(12,2) NOT NULL, "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "taxAmount" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL, "expenseDate" date NOT NULL, "dueDate" date, "paymentMethod" "public"."expenses_paymentmethod_enum" NOT NULL, "vendor" character varying(255), "receiptNumber" character varying(100), "referenceNumber" character varying(100), "notes" text, "recurrence" "public"."expenses_recurrence_enum" NOT NULL DEFAULT 'one_time', "isReimbursable" boolean NOT NULL DEFAULT false, "isReimbursed" boolean NOT NULL DEFAULT false, "reimbursedDate" date, "isTaxDeductible" boolean NOT NULL DEFAULT true, "approvedAmount" numeric(12,2) NOT NULL DEFAULT '0', "rejectionReason" text, "costCenter" character varying(100), "project" character varying(100), "department" character varying(100), "metadata" json, "submitted_by" uuid, "company_id" uuid, "branch_id" uuid, CONSTRAINT "UQ_57552c177da550b3271a2cfb646" UNIQUE ("expenseNumber"), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e069bf5f4d4aaab62a84f24ca4" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d9547156ad50bae6149482e52" ON "expenses" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f52fb01c27607bb74ba05abf16" ON "expenses" ("expenseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_c74428bcafedde6850cdacaf0a" ON "expenses" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_57552c177da550b3271a2cfb64" ON "expenses" ("expenseNumber") `);
        await queryRunner.query(`CREATE TABLE "product_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "description" text, "code" character varying(10), "isActive" boolean NOT NULL DEFAULT true, "defaultCommissionRate" numeric(5,2) NOT NULL DEFAULT '0', "defaultTaxRate" numeric(5,2) NOT NULL DEFAULT '0', "metadata" json, CONSTRAINT "PK_bccc8805f3453d0cce77c1beedb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_68e571537431790229b8a3a596" ON "product_groups" ("name") `);
        await queryRunner.query(`CREATE TABLE "discount_products" ("discount_id" uuid NOT NULL, "product_id" uuid NOT NULL, CONSTRAINT "PK_ec9bf243c94d07317493d1d6b28" PRIMARY KEY ("discount_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19155613d001de1ce3da8875d5" ON "discount_products" ("discount_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8857bc50a51861e155ce58ca41" ON "discount_products" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "discount_customers" ("discount_id" uuid NOT NULL, "customer_id" uuid NOT NULL, CONSTRAINT "PK_e29c47d0b96734d684d70dabe75" PRIMARY KEY ("discount_id", "customer_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f155905bf802cb04963b1a3849" ON "discount_customers" ("discount_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_57dd0c9475dd10cd30c4f84b86" ON "discount_customers" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "product_group_products" ("group_id" uuid NOT NULL, "product_id" uuid NOT NULL, CONSTRAINT "PK_ed0dfe10b9c036720c00e0901b1" PRIMARY KEY ("group_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eeef158e27f158b19fa4e5bc3b" ON "product_group_products" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_61d25794e7ca098f6ba9593e23" ON "product_group_products" ("product_id") `);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "warehouse_products" ADD "quantity" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "address" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "shops" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shops" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "baseCommissionRate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "creditLimit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "currentCreditBalance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "availableCredit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "creditRating"`);
        await queryRunner.query(`CREATE TYPE "public"."customers_creditrating_enum" AS ENUM('excellent', 'good', 'fair', 'poor', 'no_rating')`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "creditRating" "public"."customers_creditrating_enum" NOT NULL DEFAULT 'no_rating'`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "paymentTermsDays" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "isCreditApproved" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "interestRate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "allowCreditSales" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "commissionRate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "stockQuantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "minStockLevel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "warehouses" ALTER COLUMN "companyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum" RENAME TO "suppliers_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('active', 'inactive', 'blacklisted')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum" USING "status"::"text"::"public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b2beba6a393519038d64b12ed" ON "branches" ("name", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bdf3ec1f33c40450a9cf49b79d" ON "customers" ("phoneNumber", "companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9739cd52e8a233dcc1510857a" ON "suppliers" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_a35729a94e7280cbebaaa541a20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_5be5e14c7b17f53289a02899811" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_607224eff620e73a84b9519155e" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" ADD CONSTRAINT "FK_ccae053f04966cbfb1425f26ca7" FOREIGN KEY ("creditId") REFERENCES "credits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" ADD CONSTRAINT "FK_065eee9c3053c4f52f7bc0d996c" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_4b584773f9c412d6eec7b45539c" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_4c00a69bfdcc1daa12fabeeb0ea" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_3176a2c3cfdfc3e52a7ef2be382" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credits" ADD CONSTRAINT "FK_d1adbadda7e5a8acef6f7857b69" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_cacf9f66472cee2cb9635392892" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD CONSTRAINT "FK_98b764d1f5411357cb5d50b8bba" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD CONSTRAINT "FK_ea91320cac7908867e288ac7a81" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "FK_8f92dbc07e81c8be491d9316d15" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "FK_25e02016a81838ed10dd877c5cc" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "FK_9f222a91f08322c9d08a1b443b8" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_737991e10350d9626f592894cef" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_c7b030a4514a003d9d8d31a812b" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_9cb03e9df5b6c71b181d79720c2" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_ac44f15896b81599b45b8d6f4f0" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_6f9395c9037632a31107c8a9e58" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_7680babafb8b9ca907bfbd142c5" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_66dcc8b80d6571a4edf537bff1e" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_568c2136b0779d63539cf84fafc" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_00c5470b7884170bba20642b04c" FOREIGN KEY ("sales_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_2e62caaea771f155d11324a50fb" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD CONSTRAINT "FK_13b1ec740347b9d17257df3b9fe" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_b4ceb47b87c47ed55332ec20433" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_23d56e4b35636f1e61ffcb330df" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_3a92cf6add00043cef9833db1cd" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_7680423341c3358404990c2fecf" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_4cc004d8ae1797e47e62635f7ac" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_236f3154522de80a98f87c66b84" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_83a12e5e2723eafe9a47c441457" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_122588f5d349bcae6e6e461490a" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_fb301c26b86f95256429a2e6981" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_5a6fdf4dae16704000b9711654d" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_de1043dff8f68e83a20480b00f7" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_47942e65af8e4235d4045515f05" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_1b722234d6e60702724d0d5b423" FOREIGN KEY ("managerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_8c8f4def51a0411f95b1b4c8016" FOREIGN KEY ("sourceWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_0713446954e2d4b81c831f215b6" FOREIGN KEY ("sourceShopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_f9911ee7d284f6d7eaaacb92547" FOREIGN KEY ("destinationWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_02f4cb11e0d1e982682b269c1f5" FOREIGN KEY ("destinationShopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_9ed2455b82163fa753259d41301" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_bea0014a61ad163994ef7827134" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_items" ADD CONSTRAINT "FK_68c98df7d513511ac09e26ca9c3" FOREIGN KEY ("transferId") REFERENCES "transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_items" ADD CONSTRAINT "FK_05045a77e7c8c080ce93cffc547" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_permissions" ADD CONSTRAINT "FK_bddba2e40b167c695b346b5ebdc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_121744c3063cfae889a37384fe4" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_e72e88d348ffb035d125408a546" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_42ac2fef6580d3b369845e2a5b8" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_f76f7eb70da05acd4e2be3403d4" FOREIGN KEY ("reconciled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_caed0f51e45442af8cea5c410b2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_c430418f27a90fb62dedf135e38" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_46166001a69d40503f6b9dbf9a4" FOREIGN KEY ("received_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_0c7a111f7762b267a86d5814ed5" FOREIGN KEY ("quality_checked_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" ADD CONSTRAINT "FK_77fc075133f1d2431822e630c14" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" ADD CONSTRAINT "FK_a30df94c68e018e3854472c58a1" FOREIGN KEY ("receiving_id") REFERENCES "purchase_receivings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" ADD CONSTRAINT "FK_4318bdf33d315c84b608f336aad" FOREIGN KEY ("purchase_item_id") REFERENCES "purchase_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" ADD CONSTRAINT "FK_ce78e50ad2ef0237ec5debfb5fc" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a525d85f0ac59aa9a971825e1af" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a330ae0dd450f91c6b9c7fda688" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" ADD CONSTRAINT "FK_d6c21b14a308a4bd945743fb8d6" FOREIGN KEY ("expense_id") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" ADD CONSTRAINT "FK_0809d66cf62ff6396d7c10fe243" FOREIGN KEY ("approver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" ADD CONSTRAINT "FK_6d7084dd6a11edb3b2af62745f9" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_attachments" ADD CONSTRAINT "FK_e946f1f2ffdb088d00d21666a72" FOREIGN KEY ("expense_id") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_035cfd2ca0aea5567b55e114f9e" FOREIGN KEY ("submitted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_85389c627f20798554ac2bfb052" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_866a3b82ff438efc19c2398cda6" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_products" ADD CONSTRAINT "FK_19155613d001de1ce3da8875d57" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_products" ADD CONSTRAINT "FK_8857bc50a51861e155ce58ca410" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_customers" ADD CONSTRAINT "FK_f155905bf802cb04963b1a38493" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_customers" ADD CONSTRAINT "FK_57dd0c9475dd10cd30c4f84b865" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_group_products" ADD CONSTRAINT "FK_eeef158e27f158b19fa4e5bc3ba" FOREIGN KEY ("group_id") REFERENCES "product_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_group_products" ADD CONSTRAINT "FK_61d25794e7ca098f6ba9593e234" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_group_products" DROP CONSTRAINT "FK_61d25794e7ca098f6ba9593e234"`);
        await queryRunner.query(`ALTER TABLE "product_group_products" DROP CONSTRAINT "FK_eeef158e27f158b19fa4e5bc3ba"`);
        await queryRunner.query(`ALTER TABLE "discount_customers" DROP CONSTRAINT "FK_57dd0c9475dd10cd30c4f84b865"`);
        await queryRunner.query(`ALTER TABLE "discount_customers" DROP CONSTRAINT "FK_f155905bf802cb04963b1a38493"`);
        await queryRunner.query(`ALTER TABLE "discount_products" DROP CONSTRAINT "FK_8857bc50a51861e155ce58ca410"`);
        await queryRunner.query(`ALTER TABLE "discount_products" DROP CONSTRAINT "FK_19155613d001de1ce3da8875d57"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_866a3b82ff438efc19c2398cda6"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_85389c627f20798554ac2bfb052"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_035cfd2ca0aea5567b55e114f9e"`);
        await queryRunner.query(`ALTER TABLE "expense_attachments" DROP CONSTRAINT "FK_e946f1f2ffdb088d00d21666a72"`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" DROP CONSTRAINT "FK_6d7084dd6a11edb3b2af62745f9"`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" DROP CONSTRAINT "FK_0809d66cf62ff6396d7c10fe243"`);
        await queryRunner.query(`ALTER TABLE "expense_approvals" DROP CONSTRAINT "FK_d6c21b14a308a4bd945743fb8d6"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a330ae0dd450f91c6b9c7fda688"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a525d85f0ac59aa9a971825e1af"`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" DROP CONSTRAINT "FK_ce78e50ad2ef0237ec5debfb5fc"`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" DROP CONSTRAINT "FK_4318bdf33d315c84b608f336aad"`);
        await queryRunner.query(`ALTER TABLE "purchase_receiving_items" DROP CONSTRAINT "FK_a30df94c68e018e3854472c58a1"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_77fc075133f1d2431822e630c14"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_0c7a111f7762b267a86d5814ed5"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_46166001a69d40503f6b9dbf9a4"`);
        await queryRunner.query(`ALTER TABLE "purchase_receivings" DROP CONSTRAINT "FK_c430418f27a90fb62dedf135e38"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_caed0f51e45442af8cea5c410b2"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_f76f7eb70da05acd4e2be3403d4"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_42ac2fef6580d3b369845e2a5b8"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_e72e88d348ffb035d125408a546"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_121744c3063cfae889a37384fe4"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "staff_permissions" DROP CONSTRAINT "FK_bddba2e40b167c695b346b5ebdc"`);
        await queryRunner.query(`ALTER TABLE "transfer_items" DROP CONSTRAINT "FK_05045a77e7c8c080ce93cffc547"`);
        await queryRunner.query(`ALTER TABLE "transfer_items" DROP CONSTRAINT "FK_68c98df7d513511ac09e26ca9c3"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_bea0014a61ad163994ef7827134"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_9ed2455b82163fa753259d41301"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_02f4cb11e0d1e982682b269c1f5"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_f9911ee7d284f6d7eaaacb92547"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_0713446954e2d4b81c831f215b6"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_8c8f4def51a0411f95b1b4c8016"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_1b722234d6e60702724d0d5b423"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_47942e65af8e4235d4045515f05"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_de1043dff8f68e83a20480b00f7"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_5a6fdf4dae16704000b9711654d"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_fb301c26b86f95256429a2e6981"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_122588f5d349bcae6e6e461490a"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_83a12e5e2723eafe9a47c441457"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_236f3154522de80a98f87c66b84"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_4cc004d8ae1797e47e62635f7ac"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_7680423341c3358404990c2fecf"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_3a92cf6add00043cef9833db1cd"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_23d56e4b35636f1e61ffcb330df"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_b4ceb47b87c47ed55332ec20433"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_13b1ec740347b9d17257df3b9fe"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_2e62caaea771f155d11324a50fb"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP CONSTRAINT "FK_00c5470b7884170bba20642b04c"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_568c2136b0779d63539cf84fafc"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_66dcc8b80d6571a4edf537bff1e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_7680babafb8b9ca907bfbd142c5"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_6f9395c9037632a31107c8a9e58"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_ac44f15896b81599b45b8d6f4f0"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_9cb03e9df5b6c71b181d79720c2"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_c7b030a4514a003d9d8d31a812b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_737991e10350d9626f592894cef"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "FK_9f222a91f08322c9d08a1b443b8"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "FK_25e02016a81838ed10dd877c5cc"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "FK_8f92dbc07e81c8be491d9316d15"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP CONSTRAINT "FK_ea91320cac7908867e288ac7a81"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP CONSTRAINT "FK_98b764d1f5411357cb5d50b8bba"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_cacf9f66472cee2cb9635392892"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_d1adbadda7e5a8acef6f7857b69"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_3176a2c3cfdfc3e52a7ef2be382"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_4c00a69bfdcc1daa12fabeeb0ea"`);
        await queryRunner.query(`ALTER TABLE "credits" DROP CONSTRAINT "FK_4b584773f9c412d6eec7b45539c"`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" DROP CONSTRAINT "FK_065eee9c3053c4f52f7bc0d996c"`);
        await queryRunner.query(`ALTER TABLE "credit_transactions" DROP CONSTRAINT "FK_ccae053f04966cbfb1425f26ca7"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_607224eff620e73a84b9519155e"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_5be5e14c7b17f53289a02899811"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a16f3c2e9b291abc6790e9822ae"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_a35729a94e7280cbebaaa541a20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9739cd52e8a233dcc1510857a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdf3ec1f33c40450a9cf49b79d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2beba6a393519038d64b12ed"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum_old" AS ENUM('active', 'inactive', 'blacklisted', 'pending_approval', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" TYPE "public"."suppliers_status_enum_old" USING "status"::"text"::"public"."suppliers_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."suppliers_status_enum_old" RENAME TO "suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "warehouses" ALTER COLUMN "companyId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD "description" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_317f82e3b199a7c6015ce1aff95" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "minStockLevel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "stockQuantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "commissionRate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "allowCreditSales" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "interestRate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "isCreditApproved" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "paymentTermsDays" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "creditRating"`);
        await queryRunner.query(`DROP TYPE "public"."customers_creditrating_enum"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "creditRating" character varying(20) DEFAULT 'no_rating'`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "availableCredit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "currentCreditBalance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "creditLimit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "baseCommissionRate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shops" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shops" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "createdAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "warehouse_products" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "emergencyContact"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "emergencyContact" json`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "companyId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61d25794e7ca098f6ba9593e23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeef158e27f158b19fa4e5bc3b"`);
        await queryRunner.query(`DROP TABLE "product_group_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57dd0c9475dd10cd30c4f84b86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f155905bf802cb04963b1a3849"`);
        await queryRunner.query(`DROP TABLE "discount_customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8857bc50a51861e155ce58ca41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19155613d001de1ce3da8875d5"`);
        await queryRunner.query(`DROP TABLE "discount_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68e571537431790229b8a3a596"`);
        await queryRunner.query(`DROP TABLE "product_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57552c177da550b3271a2cfb64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74428bcafedde6850cdacaf0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52fb01c27607bb74ba05abf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d9547156ad50bae6149482e52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e069bf5f4d4aaab62a84f24ca4"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_recurrence_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_type_enum"`);
        await queryRunner.query(`DROP TABLE "expense_attachments"`);
        await queryRunner.query(`DROP TYPE "public"."expense_attachments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31743d2d28c0edce572d797c49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8e54d69943c0a15adce1ac3ab"`);
        await queryRunner.query(`DROP TABLE "expense_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."expense_approvals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expense_approvals_approvallevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20c2e6aeb3fe09613808ba1eab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a08866dd8bfcf715da55a567ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866212928289ec1112edd04ebf"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_storagetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."files_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."files_filetype_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_receiving_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65b827b253a3e00953c2f572d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_289617b91e6c6f79acf5ef3f11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4628685050edbefe5a1e7e96aa"`);
        await queryRunner.query(`DROP TABLE "purchase_receivings"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_receivings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e0fc7a6605393a9bd691cdceb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5272ac3aa931eedb14cd8789d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8be43e7dd0ae89d236418c690c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3253914487a9fa14a59831dba9"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_approvalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_purchasetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca7fd8e07266825408bced5e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c24beb35bae25c17c4ef994"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6e01fc2d8cf385bfc153d1564"`);
        await queryRunner.query(`DROP TABLE "purchase_payments"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a8c41174bc84bc88ad449d782"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_items_status_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TYPE "public"."settings_measurementsystem_enum"`);
        await queryRunner.query(`DROP TABLE "staff_permissions"`);
        await queryRunner.query(`DROP TABLE "transfer_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0333218b127ac6dbb3f7eac3bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a74701d10eb1b73b47f1d38af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6148a86991f8e5fd92d6b9c684"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad83f9fa2b36ccd2893b10a390"`);
        await queryRunner.query(`DROP TABLE "transfers"`);
        await queryRunner.query(`DROP TYPE "public"."transfers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transfers_type_enum"`);
        await queryRunner.query(`DROP TABLE "commissions"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_discounttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sales_paymenttype_enum"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transactions_transactiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transactions_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "sales_items"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_type_enum"`);
        await queryRunner.query(`DROP TABLE "shop_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7ad288fcf48c8e2faeaa5ab28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82ccf8ec4ff6e01df1a2b1e97b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_456c18cb444e722f0b86840868"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63eb2147c6929d75882ce4738e"`);
        await queryRunner.query(`DROP TABLE "credits"`);
        await queryRunner.query(`DROP TYPE "public"."credits_creditrating_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credits_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credits_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b87fa3cdbeacdfdb702e5f6dc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccae053f04966cbfb1425f26ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad93c8877579638af537171bf0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22b90d46370278846f0ef9f23f"`);
        await queryRunner.query(`DROP TABLE "credit_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."credit_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d8df244a3285386e0e7ff4877"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5be5e14c7b17f53289a0289981"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecce1591ffad0b35998e629071"`);
        await queryRunner.query(`DROP TABLE "credit_payments"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85f92bfee8f136fab50cc3feb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1a78b27ce1426491f175e034"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_customers_phone_company" ON "customers" ("phoneNumber", "companyId") `);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "warehouses_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "customers_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "employees_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "employees_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "shops_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "shops_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "shops_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "companies_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "branches_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
